### PR TITLE
add editorconfig file and format files

### PR DESCRIPTION
**Pull request by a-type**
Editorconfig (http://editorconfig.org) is a useful tool for defining basic file formatting rules like tab style and whitespace across the project. I use it at home so I needed to configure it, so that my editor would follow the general style of the code.

### CODE REVIEW

**Comment by Jackamus29** [comment]
The editorconfig is fine, but there seems to be a lot of whitespace clean up. Are these necessary?

**Comment by a-type** [comment]
The config specifies some whitespace rules for general file cleanliness, so I went through and re-saved the files to bring them into compliance. As long as there are automated rules, may as well pull everything in line. If you'd prefer not to use these editor rules, though, I'd be happy to just keep them local to my machine. I only needed them because my editor is configured to follow the `.editorconfig` guide for all formatting, so I needed to tell it how to format things.

**Comment by Jackamus29** [comment]
Makes sense, I'm afraid my editor will conflict too much. But we need the standardization and I like the cleanup that it did. Have you thought at all about PEP-8 rules? It would be cool if your editorconfig enforced those rules on the python files as well. Just thinking out loud. I'll look around for a plug in that will allow my editor to use the config.

**Comment by a-type** [comment]
I bet there's a Python linter that will enforce PEP8. Editorconfig doesn't have much scope beyond enforcing encoding, newline, tabs and trimming whitespace.

**Pull request merged**
